apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true


## Manifest file to create EKS cluster 
## Workstation is having ekctl client with IAM CLI access role(Login to workstation and do aws configure). it can create the clsuter if we apply the below manifest file. Backend it uses the cloud formation to create the EKS cluster.

## eksctl create cluster --config-file=<manifest_file> 
## eksctl create cluster -f <maniffest_file> 
## eksctl delete cluster -f <maniffest_file> 